<?php

// This is a compiled Agavi configuration file
// Generated by: AgaviRoutingConfigHandler
// Date: 2008-10-19T15:41:00+0000

$this->importRoutes(array (
  '57722974648fb550c576fa' => 
  array (
    'rxp' => '#^/$#',
    'par' => 
    array (
    ),
    'opt' => 
    array (
      'name' => '57722974648fb550c576fa',
      'stop' => true,
      'output_type' => NULL,
      'module' => 'Default',
      'action' => 'Index',
      'parameters' => 
      array (
      ),
      'ignores' => 
      array (
      ),
      'defaults' => 
      array (
      ),
      'childs' => 
      array (
      ),
      'callback' => NULL,
      'imply' => false,
      'cut' => NULL,
      'source' => NULL,
      'method' => NULL,
      'constraint' => 
      array (
      ),
      'locale' => NULL,
      'pattern_parameters' => 
      array (
      ),
      'optional_parameters' => 
      array (
      ),
      'parent' => NULL,
      'reverseStr' => '/',
      'nostops' => 
      array (
      ),
      'anchor' => 3,
    ),
    'matches' => 
    array (
    ),
  ),
  '64712027448fb550c57fbe' => 
  array (
    'rxp' => '#^/browser/$#',
    'par' => 
    array (
    ),
    'opt' => 
    array (
      'name' => '64712027448fb550c57fbe',
      'stop' => true,
      'output_type' => NULL,
      'module' => 'Fs',
      'action' => 'Index',
      'parameters' => 
      array (
      ),
      'ignores' => 
      array (
      ),
      'defaults' => 
      array (
      ),
      'childs' => 
      array (
      ),
      'callback' => NULL,
      'imply' => false,
      'cut' => NULL,
      'source' => NULL,
      'method' => 'read',
      'constraint' => 
      array (
      ),
      'locale' => NULL,
      'pattern_parameters' => 
      array (
      ),
      'optional_parameters' => 
      array (
      ),
      'parent' => NULL,
      'reverseStr' => '/browser/',
      'nostops' => 
      array (
      ),
      'anchor' => 3,
    ),
    'matches' => 
    array (
    ),
  ),
  '199372050848fb550c5886c' => 
  array (
    'rxp' => '#^/browser/list/((?P<path>.*))$#',
    'par' => 
    array (
      0 => 'path',
    ),
    'opt' => 
    array (
      'name' => '199372050848fb550c5886c',
      'stop' => true,
      'output_type' => NULL,
      'module' => 'Fs',
      'action' => 'List',
      'parameters' => 
      array (
      ),
      'ignores' => 
      array (
      ),
      'defaults' => 
      array (
      ),
      'childs' => 
      array (
      ),
      'callback' => NULL,
      'imply' => false,
      'cut' => NULL,
      'source' => NULL,
      'method' => 'read',
      'constraint' => 
      array (
      ),
      'locale' => NULL,
      'pattern_parameters' => 
      array (
        0 => 'path',
      ),
      'optional_parameters' => 
      array (
      ),
      'parent' => NULL,
      'reverseStr' => '/browser/list/(:path:)',
      'nostops' => 
      array (
      ),
      'anchor' => 3,
    ),
    'matches' => 
    array (
    ),
  ),
  '70945042148fb550c5938e' => 
  array (
    'rxp' => '#^/test/$#',
    'par' => 
    array (
    ),
    'opt' => 
    array (
      'name' => '70945042148fb550c5938e',
      'stop' => true,
      'output_type' => NULL,
      'module' => 'Default',
      'action' => 'Index',
      'parameters' => 
      array (
      ),
      'ignores' => 
      array (
      ),
      'defaults' => 
      array (
      ),
      'childs' => 
      array (
      ),
      'callback' => NULL,
      'imply' => false,
      'cut' => NULL,
      'source' => NULL,
      'method' => NULL,
      'constraint' => 
      array (
      ),
      'locale' => NULL,
      'pattern_parameters' => 
      array (
      ),
      'optional_parameters' => 
      array (
      ),
      'parent' => NULL,
      'reverseStr' => '/test/',
      'nostops' => 
      array (
      ),
      'anchor' => 3,
    ),
    'matches' => 
    array (
    ),
  ),
));

?>