<?php

// This is a compiled Agavi configuration file
// Generated by: AgaviCompileConfigHandler
// Date: 2008-10-19T15:41:00+0000

require('/usr/share/php/agavi/util/AgaviAttributeHolder.class.php');
require('/usr/share/php/agavi/util/AgaviArrayPathDefinition.class.php');
require('/usr/share/php/agavi/action/AgaviAction.class.php');
require('/usr/share/php/agavi/core/AgaviContext.class.php');
require('/usr/share/php/agavi/controller/AgaviController.class.php');
require('/usr/share/php/agavi/controller/AgaviExecutionContainer.class.php');
require('/usr/share/php/agavi/controller/AgaviOutputType.class.php');
require('/usr/share/php/agavi/filter/AgaviFilter.class.php');
require('/usr/share/php/agavi/filter/AgaviDispatchFilter.class.php');
require('/usr/share/php/agavi/filter/AgaviExecutionFilter.class.php');
require('/usr/share/php/agavi/filter/AgaviFilterChain.class.php');
require('/usr/share/php/agavi/renderer/AgaviRenderer.class.php');
require('/usr/share/php/agavi/request/AgaviRequestDataHolder.class.php');
require('/usr/share/php/agavi/request/AgaviRequest.class.php');
require('/usr/share/php/agavi/response/AgaviResponse.class.php');
require('/usr/share/php/agavi/routing/AgaviRouting.class.php');
require('/usr/share/php/agavi/storage/AgaviStorage.class.php');
require('/usr/share/php/agavi/user/AgaviUser.class.php');
require('/usr/share/php/agavi/view/AgaviTemplateLayer.class.php');
require('/usr/share/php/agavi/view/AgaviView.class.php');

?>