<?php

// This is a compiled Agavi configuration file
// Generated by: AgaviSettingConfigHandler
// Date: 2008-10-19T15:41:00+0000

AgaviConfig::fromArray(array (
  'actions.default_module' => 'Default',
  'actions.default_action' => 'Index',
  'actions.error_404_module' => 'Default',
  'actions.error_404_action' => 'Error404',
  'actions.login_module' => 'Default',
  'actions.login_action' => 'Login',
  'actions.module_disabled_module' => 'Default',
  'actions.module_disabled_action' => 'ModuleDisabled',
  'actions.secure_module' => 'Default',
  'actions.secure_action' => 'Secure',
  'actions.unavailable_module' => 'Default',
  'actions.unavailable_action' => 'Unavailable',
  'core.app_name' => 'My Project',
  'core.available' => true,
  'core.debug' => true,
  'core.modpub' => '/modpub',
  'core.use_database' => false,
  'core.use_logging' => false,
  'core.use_routing' => true,
  'core.use_security' => true,
  'core.use_translation' => false,
  'exception.default_template' => '/usr/share/php/agavi/exception/templates/shiny.php',
  'exception.templates.console' => '/usr/share/php/agavi/exception/templates/plaintext.php',
));

?>