<?php

// This is a compiled Agavi configuration file
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2008-10-19T15:40:59+0000

self::$handlers += array (
  '/var/www/project/app/config/autoload.xml' => 
  array (
    'class' => 'AgaviAutoloadConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/autoload.xsd',
      ),
    ),
  ),
  '/usr/share/php/agavi/config/defaults/autoload.xml' => 
  array (
    'class' => 'AgaviAutoloadConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/autoload.xsd',
      ),
    ),
  ),
  '/var/www/project/app/config/compile.xml' => 
  array (
    'class' => 'AgaviCompileConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/compile.xsd',
      ),
    ),
  ),
  '/usr/share/php/agavi/config/defaults/compile.xml' => 
  array (
    'class' => 'AgaviCompileConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/compile.xsd',
      ),
    ),
  ),
  '/var/www/project/app/config/settings.xml' => 
  array (
    'class' => 'AgaviSettingConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/settings.xsd',
      ),
    ),
  ),
  '/var/www/project/app/config/factories.xml' => 
  array (
    'class' => 'AgaviFactoryConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/factories.xsd',
      ),
    ),
  ),
  '/var/www/project/app/config/databases.xml' => 
  array (
    'class' => 'AgaviDatabaseConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/databases.xsd',
      ),
    ),
  ),
  '/var/www/project/app/config/action_filters.xml' => 
  array (
    'class' => 'AgaviFilterConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/filters.xsd',
      ),
    ),
  ),
  '/var/www/project/app/config/global_filters.xml' => 
  array (
    'class' => 'AgaviFilterConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/filters.xsd',
      ),
    ),
  ),
  '/var/www/project/app/config/output_types.xml' => 
  array (
    'class' => 'AgaviOutputTypeConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/output_types.xsd',
      ),
    ),
  ),
  '/var/www/project/app/config/logging.xml' => 
  array (
    'class' => 'AgaviLoggingConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/logging.xsd',
      ),
    ),
  ),
  '/var/www/project/app/config/rbac_definitions.xml' => 
  array (
    'class' => 'AgaviRbacDefinitionConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/rbac_definitions.xsd',
      ),
    ),
  ),
  '/var/www/project/app/config/routing.xml' => 
  array (
    'class' => 'AgaviRoutingConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/routing.xsd',
      ),
    ),
  ),
  '/usr/share/php/agavi/routing/soap/wsdl.xml' => 
  array (
    'class' => 'AgaviWsdlConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
      ),
    ),
  ),
  '/var/www/project/app/config/translation.xml' => 
  array (
    'class' => 'AgaviTranslationConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/translation.xsd',
      ),
    ),
  ),
  '/var/www/project/app/config/validators.xml' => 
  array (
    'class' => 'AgaviReturnArrayConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/validators.xsd',
      ),
    ),
  ),
  '/usr/share/php/agavi/config/defaults/validators.xml' => 
  array (
    'class' => 'AgaviReturnArrayConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/validators.xsd',
      ),
    ),
  ),
  '/var/www/project/app/modules/*/config/autoload.xml' => 
  array (
    'class' => 'AgaviAutoloadConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/autoload.xsd',
      ),
    ),
  ),
  '/var/www/project/app/modules/*/config/action_filters.xml' => 
  array (
    'class' => 'AgaviFilterConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/filters.xsd',
      ),
    ),
  ),
  '/var/www/project/app/modules/*/config/module.xml' => 
  array (
    'class' => 'AgaviModuleConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/module.xsd',
      ),
    ),
  ),
  '/var/www/project/app/modules/*/validate/*.xml' => 
  array (
    'class' => 'AgaviValidatorConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/validators.xsd',
      ),
    ),
  ),
  '/var/www/project/app/modules/*/cache/*.xml' => 
  array (
    'class' => 'AgaviCachingConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
        0 => '/usr/share/php/agavi/config/xsd/caching.xsd',
      ),
    ),
  ),
  '/usr/share/php/agavi/translation/data/locales/*.xml' => 
  array (
    'class' => 'AgaviLdmlConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
      ),
    ),
  ),
  '/usr/share/php/agavi/translation/data/supplementalData.xml' => 
  array (
    'class' => 'AgaviLdmlSupplementalConfigHandler',
    'parameters' => 
    array (
    ),
    'validation' => 
    array (
      'relax_ng' => 
      array (
      ),
      'schematron' => 
      array (
      ),
      'xml_schema' => 
      array (
      ),
    ),
  ),
)

?>