<?php

// This is a compiled Agavi configuration file
// Generated by: AgaviFilterConfigHandler
// Date: 2008-10-19T15:41:00+0000

$filter = new AgaviExecutionTimeFilter();
$filter->initialize($this->context, array (
  'comment' => true,
  'output_types' => 
  array (
    0 => 'html',
  ),
));
$filters[] = $filter;

?>