<?php

// This is a compiled Agavi configuration file
// Generated by: AgaviOutputTypeConfigHandler
// Date: 2008-10-19T15:41:00+0000

$ot = new AgaviOutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'text/html; charset=UTF-8',
  ),
), 'html', array (
  'php' => 
  array (
    'class' => 'AgaviPhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
      'assigns' => 
      array (
        'routing' => 'ro',
        'request' => 'rq',
        'controller' => 'ct',
        'user' => 'us',
        'translation_manager' => 'tm',
        'request_data' => 'rd',
      ),
    ),
  ),
), 'php', array (
  'default' => 
  array (
    'layers' => 
    array (
      'content' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
    ),
    'parameters' => 
    array (
    ),
  ),
), 'default', NULL);
$this->outputTypes["html"] = $ot;
$this->defaultOutputType = "html";

?>