<?php

// This is a compiled Agavi configuration file
// Generated by: AgaviModuleConfigHandler
// Date: 2008-10-19T15:41:00+0000

AgaviConfig::fromArray(array (
  'modules.fs.enabled' => true,
  'modules.fs.title' => 'Fs Module',
  'modules.fs.version' => '',
  'modules.fs.authors' => 
  array (
    0 => '',
  ),
  'modules.fs.homepage' => '',
  'modules.fs.update_url' => '',
  'modules.fs.description' => '',
));

?>